package net.fluffybumblebee.quarkcrystals.block;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.registry.OxidizableBlocksRegistry;
import net.fluffybumblebee.quarkcrystals.block.custom.*;
import net.fluffybumblebee.quarkcrystals.util.ArrayDiscriminatorUtil;
import net.fluffybumblebee.quarkcrystals.util.IdentifierUtil;
import net.minecraft.item.BlockItem;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class QCBlocks {

    public static final CorundumCluster BLACK_CLUSTER = new CorundumCluster();
    public static final CorundumCluster BLUE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster CYAN_CLUSTER = new CorundumCluster();
    public static final CorundumCluster GREEN_CLUSTER = new CorundumCluster();
    public static final CorundumCluster INDIGO_CLUSTER = new CorundumCluster();
    public static final CorundumCluster ORANGE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster RED_CLUSTER = new CorundumCluster();
    public static final CorundumCluster PINK_CLUSTER = new CorundumCluster();
    public static final CorundumCluster WHITE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster YELLOW_CLUSTER = new CorundumCluster();
    public static final CorundumBlock BLACK_CORUNDUM = new CorundumBlock(false, 1);
    public static final CorundumBlock BLUE_CORUNDUM = new CorundumBlock(false, 2);
    public static final CorundumBlock CYAN_CORUNDUM = new CorundumBlock(false, 10);
    public static final CorundumBlock GREEN_CORUNDUM = new CorundumBlock(false, 3);
    public static final CorundumBlock INDIGO_CORUNDUM = new CorundumBlock(false, 4);
    public static final CorundumBlock ORANGE_CORUNDUM = new CorundumBlock(false, 5);
    public static final CorundumBlock RED_CORUNDUM = new CorundumBlock(false, 6);
    public static final CorundumBlock PINK_CORUNDUM = new CorundumBlock(false, 7);
    public static final CorundumBlock WHITE_CORUNDUM = new CorundumBlock(false, 8);
    public static final CorundumBlock YELLOW_CORUNDUM = new CorundumBlock(false, 9);
    public static final CrystalBlock BLACK_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock BLUE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock CYAN_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock GREEN_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock INDIGO_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock ORANGE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock RED_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock PINK_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock WHITE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock YELLOW_CRYSTAL = new CrystalBlock();
    public static final CorundumCrystalPane BLACK_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BLUE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane CYAN_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane GREEN_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane INDIGO_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane ORANGE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane RED_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane VIOLET_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane WHITE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane YELLOW_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BLACK_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BLUE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane CYAN_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane GREEN_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane INDIGO_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane ORANGE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane RED_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane PINK_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane WHITE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane YELLOW_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumBlock WAXED_BLACK_CORUNDUM = new CorundumBlock(true, 1);
    public static final CorundumBlock WAXED_BLUE_CORUNDUM = new CorundumBlock(true, 2);
    public static final CorundumBlock WAXED_CYAN_CORUNDUM = new CorundumBlock(true, 10);
    public static final CorundumBlock WAXED_GREEN_CORUNDUM = new CorundumBlock(true, 3);
    public static final CorundumBlock WAXED_INDIGO_CORUNDUM = new CorundumBlock(true, 4);
    public static final CorundumBlock WAXED_ORANGE_CORUNDUM = new CorundumBlock(true, 5);
    public static final CorundumBlock WAXED_RED_CORUNDUM = new CorundumBlock(true, 6);
    public static final CorundumBlock WAXED_PINK_CORUNDUM = new CorundumBlock(true, 7);
    public static final CorundumBlock WAXED_WHITE_CORUNDUM = new CorundumBlock(true, 8);
    public static final CorundumBlock WAXED_YELLOW_CORUNDUM = new CorundumBlock(true, 9);
    public static void registerBlocks() {
        //Corundum
        //Block
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(1)), ArrayDiscriminatorUtil.getCorundum[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(2)), ArrayDiscriminatorUtil.getCorundum[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(3)), ArrayDiscriminatorUtil.getCorundum[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(4)), ArrayDiscriminatorUtil.getCorundum[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(5)), ArrayDiscriminatorUtil.getCorundum[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(6)), ArrayDiscriminatorUtil.getCorundum[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(7)), ArrayDiscriminatorUtil.getCorundum[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(8)), ArrayDiscriminatorUtil.getCorundum[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(9)), ArrayDiscriminatorUtil.getCorundum[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(10)), ArrayDiscriminatorUtil.getCorundum[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        //Pane
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(1)),ArrayDiscriminatorUtil.getCorundumPane[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(2)), ArrayDiscriminatorUtil.getCorundumPane[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(3)), ArrayDiscriminatorUtil.getCorundumPane[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(4)), ArrayDiscriminatorUtil.getCorundumPane[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(5)), ArrayDiscriminatorUtil.getCorundumPane[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(6)), ArrayDiscriminatorUtil.getCorundumPane[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(7)), ArrayDiscriminatorUtil.getCorundumPane[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(8)), ArrayDiscriminatorUtil.getCorundumPane[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(9)), ArrayDiscriminatorUtil.getCorundumPane[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(10)), ArrayDiscriminatorUtil.getCorundumPane[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        //Crystal
        //Block
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(1)), ArrayDiscriminatorUtil.getCrystal[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(2)), ArrayDiscriminatorUtil.getCrystal[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(3)), ArrayDiscriminatorUtil.getCrystal[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(4)), ArrayDiscriminatorUtil.getCrystal[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(5)), ArrayDiscriminatorUtil.getCrystal[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(6)), ArrayDiscriminatorUtil.getCrystal[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(7)), ArrayDiscriminatorUtil.getCrystal[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(8)), ArrayDiscriminatorUtil.getCrystal[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(9)), ArrayDiscriminatorUtil.getCrystal[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(10)), ArrayDiscriminatorUtil.getCrystal[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        //Pane
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(1)),ArrayDiscriminatorUtil.getCrystalPane[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(2)), ArrayDiscriminatorUtil.getCrystalPane[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(3)), ArrayDiscriminatorUtil.getCrystalPane[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(4)), ArrayDiscriminatorUtil.getCrystalPane[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(5)), ArrayDiscriminatorUtil.getCrystalPane[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(6)), ArrayDiscriminatorUtil.getCrystalPane[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(7)), ArrayDiscriminatorUtil.getCrystalPane[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(8)), ArrayDiscriminatorUtil.getCrystalPane[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(9)), ArrayDiscriminatorUtil.getCrystalPane[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(10)), ArrayDiscriminatorUtil.getCrystalPane[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        //Clusters
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(1)),ArrayDiscriminatorUtil.getCorundumCluster[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(2)), ArrayDiscriminatorUtil.getCorundumCluster[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(3)), ArrayDiscriminatorUtil.getCorundumCluster[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(4)), ArrayDiscriminatorUtil.getCorundumCluster[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(5)), ArrayDiscriminatorUtil.getCorundumCluster[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(6)), ArrayDiscriminatorUtil.getCorundumCluster[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(7)), ArrayDiscriminatorUtil.getCorundumCluster[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(8)), ArrayDiscriminatorUtil.getCorundumCluster[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(9)), ArrayDiscriminatorUtil.getCorundumCluster[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(10)), ArrayDiscriminatorUtil.getCorundumCluster[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(1)), ArrayDiscriminatorUtil.getWaxedCorundum[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(1)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[1], ArrayDiscriminatorUtil.getWaxedCorundum[1]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(2)), ArrayDiscriminatorUtil.getWaxedCorundum[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(2)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[2], ArrayDiscriminatorUtil.getWaxedCorundum[2]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(3)), ArrayDiscriminatorUtil.getWaxedCorundum[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(3)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[3], ArrayDiscriminatorUtil.getWaxedCorundum[3]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(4)), ArrayDiscriminatorUtil.getWaxedCorundum[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(4)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[4], ArrayDiscriminatorUtil.getWaxedCorundum[4]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(5)), ArrayDiscriminatorUtil.getWaxedCorundum[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(5)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[5], ArrayDiscriminatorUtil.getWaxedCorundum[5]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(6)), ArrayDiscriminatorUtil.getWaxedCorundum[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(6)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[6], ArrayDiscriminatorUtil.getWaxedCorundum[6]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(7)), ArrayDiscriminatorUtil.getWaxedCorundum[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(7)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[7], ArrayDiscriminatorUtil.getWaxedCorundum[7]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(8)), ArrayDiscriminatorUtil.getWaxedCorundum[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(8)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[8], ArrayDiscriminatorUtil.getWaxedCorundum[8]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(9)), ArrayDiscriminatorUtil.getWaxedCorundum[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(9)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[9], ArrayDiscriminatorUtil.getWaxedCorundum[9]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(10)), ArrayDiscriminatorUtil.getWaxedCorundum[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(10)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[10], ArrayDiscriminatorUtil.getWaxedCorundum[10]);
    }
}
